name: dock_visualizer
channels:
  - defaults
dependencies:
  - python
  - streamlit
  - conda-forge::rdkit
  - py3dmol
  - ipython_genutils
  - spyrmsd
  - pip
  - stmol
  - pip:
    - posebusters
    - stmol
