name: dock_visualizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - streamlit
  - rdkit
  - py3dmol
  - ipython_genutils
  - spyrmsd
  - pip
  - pip:
    - posebusters
    - stmol